  before_build:
    - nuget restore Ghpr.NUnitExamples/Ghpr.NUnitExamples.sln

  build_script: 
    - msbuild Ghpr.NUnitExamples/Ghpr.NUnitExamples.sln /p:Configuration=Release /t:Rebuild
  
  test:
    assemblies:
      - '**\*Tests.dll'
      - '**\*Examples.dll'
    categories:
      only:
        - SuccessCategory
